blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    # path('', views.PostListView.as_view(), name='post_list'),
    path("tag/<slug:tag_slug>/", views.post_list, name="post_list_by_tag"),
    path(
       '<int:year>/<int:month>/<int:day>/<slug:post>/', 
        views.post_detail,
        name='post_detail',
    ),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('<int:post_id>/comment/', views.post_comment, name='post_comment'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("blog/", include('blog.urls', namespace='blog')),
]

blog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils import timezone
from taggit.managers import TaggableManager

# Create your models here.
class PublishedManager(models.Manager):
   def get_queryset(self):
      return super().get_queryset().filter(status=Post.Status.PUBLISHED)


class Post(models.Model):
   
   class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'
   
   title = models.CharField(max_length=250)
   slug = models.SlugField(max_length=250, unique_for_date='publish')
   author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
   body = models.TextField()
   publish = models.DateTimeField(default=timezone.now)
   created = models.DateTimeField(auto_now_add=True)
   updated = models.DateTimeField(auto_now=True)
   status = models.CharField(max_length=2,
                              choices=Status.choices,
                              default=Status.DRAFT)
   
   objects = models.Manager()
   published = PublishedManager()
   tags = TaggableManager()

   class Meta:
      ordering = ['-publish']
      indexes = [
         models.Index(fields=['-publish']),
      ]

   def __str__(self) -> str:
      return self.title
   
   def get_absolute_url(self):
        return reverse("blog:post_detail", args=[self.publish.year,
                                                 self.publish.month,
                                                 self.publish.day,
                                                 self.slug])

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['created']
        indexes = [
            models.Index(fields=['created']),
        ]

    def __str__(self) -> str:
        return f'Comment by {self.name} on {self.post}'

blog/forms.py
from django import forms
from .models import Post, Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["name", "email", "body"]


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)

blog/views.py
from django.db.models import Count
from django.core.mail import send_mail
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import Http404
from django.shortcuts import render, get_object_or_404
from django.views.decorators.http import require_POST
from django.views.generic import ListView
from taggit.models import Tag

from .forms import CommentForm, EmailPostForm
from .models import Post

class PostListView(ListView):
    """Альтернативне подання списку постів"""
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'

def post_list(request, tag_slug=None):
    post_list = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        post_list = post_list.filter(tags__in=[tag])
    # Посторінкове розбиття з 3 постами на сторінку
    paginator = Paginator(post_list, 3)
    page_number = request.GET.get('page', 1)
    try:
        posts = paginator.page(page_number)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    except PageNotAnInteger:
        posts = paginator.page(1)
    return render(request, 'blog/post/list.html', {'posts': posts, 'tag': tag})


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post, status=Post.Status.PUBLISHED,
                             publish__year=year,
                             publish__month=month,
                             publish__day=day)
    comments = post.comments.filter(active=True)
    form = CommentForm()
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', 'publish')[:4]
    return render(request, "blog/post/detail.html", {"post": post, 'comments': comments, 'form': form, "similar_posts": similar_posts})

def post_share(request, post_id):
    # Отримати пост за id
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    sent = False
    if request.method == 'POST':
        # Форма передана на обробку
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Поля форми успішно пройшли валідацію
            cd = form.cleaned_data
            # відправити електронного листа
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f'{cd["name"]} recommends you read {post.title}'
            message = f'Read {post.title} at {post_url}\n\n' \
                      f'{cd["name"]}\'s comments: {cd["comments"]}'
            send_mail(subject, message, 'your_account@gmail.com', [cd['to']])
            sent = True              
    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post, 'form': form, 'sent': sent})

@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    comment = None
    form = CommentForm(data=request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.save()
    return render(
        request,
        "blog/post/comment.html",
        context={
            "post": post,
            "form": form,
            "comment": comment,
        }
    )

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock  %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-8" id="content">
                {% block content %}
                {% endblock content %}
            </div>
            <div class="col-md-4 p-2 bg-body-secondary" id="sidebar">
                <h2>My blog</h2>
                <p>This is my blog</p>
            </div>
        </div>
        <footer class="bg-warning bg-gradient mt-3 p-5 text-center text-primary rounded">
            <i class="bi bi-c-circle"></i> Python Web, 2023
        </footer>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

blog/templates/blog/post/comment.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}

{% block title %}Add a comment{% endblock title %}

{% block content %}
{% if comment %}
    <h2>Your comment has been added.</h2>
    <p><a href="{{ post.get_absolute_url }}">Back to the post</a></p>
{% else %}
    {% include "blog/post/includes/comment_form.html" %}
{% endif %}
{% endblock content %}

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}

{% block title %} {{ post.title }} {% endblock  %}

{% block content %}
    <h1 class="border-bottom border-2 pb-2">{{ post.title }}</h1>
    <p class="date fst-italic text-secondary">
        Published {{ post.publish }} by {{ post.author }}
    </p>
    {{ post.body|linebreaks }}
    <p>
        <a href="{% url 'blog:post_share' post.id %}">
            Share this post
        </a>
    </p>
    <h2>Similar posts</h2>
    {% for post in similar_posts %}
        <p>
            <a href="{{ post.get_absolute_url }}" class="text-decoration-none">{{ post.title }}</a>
        </p>
    {% empty %}
        There are no similar posts yet.
    {% endfor %}
    {% with total_comments=comments.count %}
    <h2>
        {{ total_comments }} comment{{ total_comments|pluralize }}
    </h2>
    {% endwith %}
    {% for comment in comments %}
    <div class="comment">
        <p class="info fw-bold">
            #{{ forloop.counter }} by {{ comment.name }}
        </p>
        <div class="ms-5">
            {{ comment.body|linebreaks }}
        </div>
        <p class="fw-light fst-italic text-end" style="font-size: 0.8rem;">
            {{ comment.created }}
        </p>
    </div>
    {% empty %}
    <p>There are no comments.</p>
    {% endfor %}
    {% include "blog/post/includes/comment_form.html" %}
{% endblock content %}

blog/templates/blog/post/includes/comment_form.html
{% load crispy_forms_tags %}

<h2>Add a new comment</h2>
<form action="{% url 'blog:post_comment' post.id %}" method="post">
    {{ form|crispy }}
    {% csrf_token %}
    <p><input type="submit" value="Add comment"></p>
</form>

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}

{% block title %}My blog{% endblock %}

{% block content %}
    <h1 class="border-bottom border-2 pb-2">My Blog</h1>
    {% if tag %}
    <h2>Posts tagged with "{{ tag.name }}"</h2>
    {% endif %}
    {% for post in posts %}
    <h2>
        <a class="text-decoration-none" href="{{ post.get_absolute_url }}">
            {{ post.title}}
        </a>
    </h2>
    <p class="date fst-italic text-secondary">
        Published {{ post.publish }} by {{ post.author }}
    </p>
    <div>
        {{ post.body|truncatewords:30|linebreaks }}
    </div>
    <p class="tags fw-semibold text-secondary border-bottom">
    {% for tag in post.tags.all %}
        <a class="text-decoration-none" href="{% url 'blog:post_list_by_tag' tag.slug %}">{{ tag.name }}</a>
        {% if not forloop.last %}, {% endif %}
    {% endfor %}
    </p>
    {% endfor %}
    {% include "pagination.html" with page=posts %}
{% endblock content %}

blog/templates/blog/post/share.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block title %}Share a post{% endblock %}

{% block content %}
    {% if sent %}
    <h1>E-mail was successfully sent</h1>
    <p>
        "{{ post.title }}" was successfully sent
        to {{ form.cleaned_data.to }}.
    </p>
    {% else %}
    <h1>Share "{{ post.title }}" by e-mail</h1>
    <form method="post">
        {{ form|crispy }}
        {% csrf_token %}
        <input type="submit" value="Send e-mail">
    </form>
    {% endif %}
{% endblock content %}

blog/templates/pagination.html
<nav aria-label="Page navigation" class="mt-3 d-flex justify-content-center">
   <ul class="pagination">
       {% if page.has_previous %}
       <li class="page-item">
           <a class="page-link" href="?page={{ page.previous_page_number }}">Previous</a>
       </li>
       {% endif %}
       <li class="page-item"><a class="page-link" href="#">{{ page.number }} of {{ page.paginator.num_pages }}</a></li>
       {% if page.has_next %}
       <li class="page-item">
           <a class="page-link" href="?page={{ page.next_page_number }}">Next</a>
       </li>
       {% endif %}
   </ul>
</nav>